import 'package:plantapp/services/library_service.dart';

/// Fixed list of 28 popular plants for Library home screen.
/// Photos hosted on Cloudinary CDN — permanent URLs, auto-resize.
/// Update this list when you want to change featured plants.
const featuredPlants = <LibraryPlant>[
  LibraryPlant(id: 0, plantIdStr: 'monstera_deliciosa', scientific: 'Monstera deliciosa', commonName: 'Monstera', family: 'Araceae', imageUrl: 'https://res.cloudinary.com/dmvvh57hg/image/upload/plants/monstera_deliciosa/main.jpg', careLevel: 'Medium', watering: 'Every 7-10 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'epipremnum_aureum', scientific: 'Epipremnum aureum', commonName: 'Pothos', family: 'Araceae', imageUrl: 'https://res.cloudinary.com/dmvvh57hg/image/upload/plants/epipremnum_aureum/main.jpg', careLevel: 'Easy', watering: 'Every 7-10 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'dracaena_trifasciata', scientific: 'Dracaena trifasciata', commonName: 'Snake Plant', family: 'Asparagaceae', imageUrl: 'https://res.cloudinary.com/dmvvh57hg/image/upload/plants/dracaena_trifasciata/main.jpg', careLevel: 'Easy', watering: 'Every 2-3 weeks', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'crassula_ovata', scientific: 'Crassula ovata', commonName: 'Jade Plant', family: 'Crassulaceae', imageUrl: 'https://res.cloudinary.com/dmvvh57hg/image/upload/plants/crassula_ovata/main.jpg', careLevel: 'Easy', watering: 'Every 2-3 weeks', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'spathiphyllum_wallisii', scientific: 'Spathiphyllum wallisii', commonName: 'Peace Lily', family: 'Araceae', imageUrl: 'https://res.cloudinary.com/dmvvh57hg/image/upload/plants/spathiphyllum_wallisii/main.jpg', careLevel: 'Easy', watering: 'Every 5-7 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'ficus_lyrata', scientific: 'Ficus lyrata', commonName: 'Fiddle Leaf Fig', family: 'Moraceae', imageUrl: 'https://res.cloudinary.com/dmvvh57hg/image/upload/plants/ficus_lyrata/main.jpg', careLevel: 'Medium', watering: 'Every 7-10 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'ficus_elastica', scientific: 'Ficus elastica', commonName: 'Rubber Plant', family: 'Moraceae', imageUrl: 'https://res.cloudinary.com/dmvvh57hg/image/upload/plants/ficus_elastica/main.jpg', careLevel: 'Medium', watering: 'Every 7-10 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'aloe_vera', scientific: 'Aloe vera', commonName: 'Aloe Vera', family: 'Asphodelaceae', imageUrl: 'https://res.cloudinary.com/dmvvh57hg/image/upload/plants/aloe_vera/main.png', careLevel: 'Easy', watering: 'Every 2-3 weeks', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'zamioculcas_zamiifolia', scientific: 'Zamioculcas zamiifolia', commonName: 'ZZ Plant', family: 'Araceae', imageUrl: 'https://res.cloudinary.com/dmvvh57hg/image/upload/plants/zamioculcas_zamiifolia/main.jpg', careLevel: 'Easy', watering: 'Every 2-3 weeks', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'chlorophytum_comosum', scientific: 'Chlorophytum comosum', commonName: 'Spider Plant', family: 'Asparagaceae', imageUrl: 'https://res.cloudinary.com/dmvvh57hg/image/upload/plants/chlorophytum_comosum/main.jpg', careLevel: 'Easy', watering: 'Every 7-10 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'phalaenopsis_amabilis', scientific: 'Phalaenopsis amabilis', commonName: 'Moth Orchid', family: 'Orchidaceae', imageUrl: 'https://res.cloudinary.com/dmvvh57hg/image/upload/plants/phalaenopsis_amabilis/main.jpg', careLevel: 'Medium', watering: 'Every 7-10 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'calathea_orbifolia', scientific: 'Calathea orbifolia', commonName: 'Calathea Orbifolia', family: 'Marantaceae', imageUrl: 'https://res.cloudinary.com/dmvvh57hg/image/upload/plants/calathea_orbifolia/main.jpg', careLevel: 'Medium', watering: 'Every 5-7 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'dracaena_marginata', scientific: 'Dracaena marginata', commonName: 'Dragon Tree', family: 'Asparagaceae', imageUrl: 'https://res.cloudinary.com/dmvvh57hg/image/upload/plants/dracaena_marginata/main.jpg', careLevel: 'Easy', watering: 'Every 7-10 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'philodendron_hederaceum', scientific: 'Philodendron hederaceum', commonName: 'Heartleaf Philodendron', family: 'Araceae', imageUrl: 'https://res.cloudinary.com/dmvvh57hg/image/upload/plants/philodendron_hederaceum/main.jpg', careLevel: 'Easy', watering: 'Every 7-10 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'monstera_adansonii', scientific: 'Monstera adansonii', commonName: 'Swiss Cheese Vine', family: 'Araceae', imageUrl: 'https://res.cloudinary.com/dmvvh57hg/image/upload/plants/monstera_adansonii/main.jpg', careLevel: 'Medium', watering: 'Every 5-7 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'ocimum_basilicum', scientific: 'Ocimum basilicum', commonName: 'Basil', family: 'Lamiaceae', imageUrl: 'https://res.cloudinary.com/dmvvh57hg/image/upload/plants/ocimum_basilicum/main.jpg', careLevel: 'Easy', watering: 'Every 2-3 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'rosmarinus_officinalis', scientific: 'Salvia rosmarinus', commonName: 'Rosemary', family: 'Lamiaceae', imageUrl: 'https://res.cloudinary.com/dmvvh57hg/image/upload/plants/rosmarinus_officinalis/main.jpg', careLevel: 'Medium', watering: 'Every 7-10 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'solanum_lycopersicum', scientific: 'Solanum lycopersicum', commonName: 'Cherry Tomato', family: 'Solanaceae', imageUrl: 'https://res.cloudinary.com/dmvvh57hg/image/upload/plants/solanum_lycopersicum/main.jpg', careLevel: 'Medium', watering: 'Every 1-2 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'nephrolepis_exaltata', scientific: 'Nephrolepis exaltata', commonName: 'Boston Fern', family: 'Polypodiaceae', imageUrl: 'https://res.cloudinary.com/dmvvh57hg/image/upload/plants/nephrolepis_exaltata/main.jpg', careLevel: 'Easy', watering: 'Every 5-7 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'anthurium_andraeanum', scientific: 'Anthurium andraeanum', commonName: 'Anthurium', family: 'Araceae', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/8b/AnthuriumAndraenum.jpg', careLevel: 'Medium', watering: 'Every 7-10 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'strelitzia_nicolai', scientific: 'Strelitzia nicolai', commonName: 'Bird of Paradise', family: 'Strelitziaceae', imageUrl: 'https://res.cloudinary.com/dmvvh57hg/image/upload/plants/strelitzia_nicolai/main.jpg', careLevel: 'Easy', watering: 'Every 7-10 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'echeveria_elegans', scientific: 'Echeveria elegans', commonName: 'Echeveria', family: 'Crassulaceae', imageUrl: 'https://res.cloudinary.com/dmvvh57hg/image/upload/plants/echeveria_elegans/main.png', careLevel: 'Easy', watering: 'Every 2-3 weeks', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'mentha_spicata', scientific: 'Mentha spicata', commonName: 'Mint', family: 'Lamiaceae', imageUrl: 'https://res.cloudinary.com/dmvvh57hg/image/upload/plants/mentha_spicata/main.jpg', careLevel: 'Easy', watering: 'Every 3-5 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'dieffenbachia_seguine', scientific: 'Dieffenbachia seguine', commonName: 'Dumb Cane', family: 'Araceae', imageUrl: 'https://res.cloudinary.com/dmvvh57hg/image/upload/plants/dieffenbachia_seguine/main.jpg', careLevel: 'Medium', watering: 'Every 5-7 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'lavandula_angustifolia', scientific: 'Lavandula angustifolia', commonName: 'Lavender', family: 'Lamiaceae', imageUrl: 'https://res.cloudinary.com/dmvvh57hg/image/upload/plants/lavandula_angustifolia/main.jpg', careLevel: 'Easy', watering: 'Every 7-10 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'dracaena_fragrans', scientific: 'Dracaena fragrans', commonName: 'Corn Plant', family: 'Asparagaceae', imageUrl: 'https://res.cloudinary.com/dmvvh57hg/image/upload/plants/dracaena_fragrans/main.jpg', careLevel: 'Easy', watering: 'Every 7-10 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'dypsis_lutescens', scientific: 'Dypsis lutescens', commonName: 'Areca Palm', family: 'Arecaceae', imageUrl: 'https://res.cloudinary.com/dmvvh57hg/image/upload/plants/dypsis_lutescens/main.jpg', careLevel: 'Medium', watering: 'Every 7-10 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'cycas_revoluta', scientific: 'Cycas revoluta', commonName: 'Sago Palm', family: 'Cycadaceae', imageUrl: 'https://res.cloudinary.com/dmvvh57hg/image/upload/plants/cycas_revoluta/main.jpg', careLevel: 'Medium', watering: 'Every 7-10 days', indoor: true),
];
