import 'package:plantapp/services/library_service.dart';

/// Fixed list of 28 popular plants for Library home screen.
/// Loaded instantly — no API call needed.
/// Update this list when you want to change featured plants.
const featuredPlants = <LibraryPlant>[
  LibraryPlant(id: 0, plantIdStr: 'monstera_deliciosa', scientific: 'Monstera deliciosa', commonName: 'Monstera', family: 'Araceae', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Monstera_deliciosa2.jpg/330px-Monstera_deliciosa2.jpg', careLevel: 'Medium', watering: 'Every 7-10 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'epipremnum_aureum', scientific: 'Epipremnum aureum', commonName: 'Pothos', family: 'Araceae', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/62/Money_Plant_%28Epipremnum_aureum%29_4.jpg', careLevel: 'Easy', watering: 'Every 7-10 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'dracaena_trifasciata', scientific: 'Dracaena trifasciata', commonName: 'Snake Plant', family: 'Asparagaceae', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Snake_Plant_%28Sansevieria_trifasciata_%27Laurentii%27%29.jpg/330px-Snake_Plant_%28Sansevieria_trifasciata_%27Laurentii%27%29.jpg', careLevel: 'Easy', watering: 'Every 2-3 weeks', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'crassula_ovata', scientific: 'Crassula ovata', commonName: 'Jade Plant', family: 'Crassulaceae', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Crassula_ovata_700.jpg/330px-Crassula_ovata_700.jpg', careLevel: 'Easy', watering: 'Every 2-3 weeks', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'spathiphyllum_wallisii', scientific: 'Spathiphyllum wallisii', commonName: 'Peace Lily', family: 'Araceae', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Spathiphyllum_cochlearispathum_RTBG.jpg/330px-Spathiphyllum_cochlearispathum_RTBG.jpg', careLevel: 'Easy', watering: 'Every 5-7 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'ficus_lyrata', scientific: 'Ficus lyrata', commonName: 'Fiddle Leaf Fig', family: 'Moraceae', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/84/Starr_031108-0130_Ficus_lyrata.jpg', careLevel: 'Medium', watering: 'Every 7-10 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'ficus_elastica', scientific: 'Ficus elastica', commonName: 'Rubber Plant', family: 'Moraceae', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/16/Ficus_elastica_leaves_02.JPG', careLevel: 'Medium', watering: 'Every 7-10 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'aloe_vera', scientific: 'Aloe vera', commonName: 'Aloe Vera', family: 'Asphodelaceae', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Aloe_vera_flower_inset.png', careLevel: 'Easy', watering: 'Every 2-3 weeks', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'zamioculcas_zamiifolia', scientific: 'Zamioculcas zamiifolia', commonName: 'ZZ Plant', family: 'Araceae', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Zamioculcas_zamiifolia_1.jpg/330px-Zamioculcas_zamiifolia_1.jpg', careLevel: 'Easy', watering: 'Every 2-3 weeks', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'chlorophytum_comosum', scientific: 'Chlorophytum comosum', commonName: 'Spider Plant', family: 'Asparagaceae', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Hierbabuena_0611_Revised.jpg/330px-Hierbabuena_0611_Revised.jpg', careLevel: 'Easy', watering: 'Every 7-10 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'phalaenopsis_amabilis', scientific: 'Phalaenopsis amabilis', commonName: 'Moth Orchid', family: 'Orchidaceae', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Phalaenopsis_amabilis_Orchi_198.jpg/330px-Phalaenopsis_amabilis_Orchi_198.jpg', careLevel: 'Medium', watering: 'Every 7-10 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'calathea_orbifolia', scientific: 'Calathea orbifolia', commonName: 'Calathea', family: 'Marantaceae', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Calathea_orbifolia_2.jpg/330px-Calathea_orbifolia_2.jpg', careLevel: 'Medium', watering: 'Every 5-7 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'dracaena_marginata', scientific: 'Dracaena marginata', commonName: 'Dragon Tree', family: 'Asparagaceae', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/61/Dracaena_reflexa.JPG', careLevel: 'Easy', watering: 'Every 7-10 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'philodendron_hederaceum', scientific: 'Philodendron hederaceum', commonName: 'Heartleaf Philodendron', family: 'Araceae', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Philodendron_scandens_subsp_oxycardium2.jpg/330px-Philodendron_scandens_subsp_oxycardium2.jpg', careLevel: 'Easy', watering: 'Every 7-10 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'monstera_adansonii', scientific: 'Monstera adansonii', commonName: 'Swiss Cheese Vine', family: 'Araceae', imageUrl: 'https://bs.plantnet.org/image/o/38d4346034e89f4e5917357f2bc62cdcd150a3af', careLevel: 'Medium', watering: 'Every 5-7 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'ocimum_basilicum', scientific: 'Ocimum basilicum', commonName: 'Basil', family: 'Lamiaceae', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Ocimum_basilicum_8zz.jpg/330px-Ocimum_basilicum_8zz.jpg', careLevel: 'Easy', watering: 'Every 2-3 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'rosmarinus_officinalis', scientific: 'Salvia rosmarinus', commonName: 'Rosemary', family: 'Lamiaceae', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Rosemary_in_bloom.JPG/330px-Rosemary_in_bloom.JPG', careLevel: 'Medium', watering: 'Every 7-10 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'solanum_lycopersicum', scientific: 'Solanum lycopersicum', commonName: 'Cherry Tomato', family: 'Solanaceae', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Cherry_tomatoes_red_and_green_2009_16x9.jpg/330px-Cherry_tomatoes_red_and_green_2009_16x9.jpg', careLevel: 'Medium', watering: 'Every 1-2 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'nephrolepis_exaltata', scientific: 'Nephrolepis exaltata', commonName: 'Boston Fern', family: 'Polypodiaceae', imageUrl: 'https://bs.plantnet.org/image/o/d0314c380dec74511ee7420fae9bcbba6bc7abc4', careLevel: 'Easy', watering: 'Every 5-7 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'anthurium_andraeanum', scientific: 'Anthurium andraeanum', commonName: 'Anthurium', family: 'Araceae', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/8b/AnthuriumAndraenum.jpg', careLevel: 'Medium', watering: 'Every 7-10 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'strelitzia_nicolai', scientific: 'Strelitzia nicolai', commonName: 'Bird of Paradise', family: 'Strelitziaceae', imageUrl: 'https://bs.plantnet.org/image/o/95d1edec7a7a2a143e0427854969154d4b656442', careLevel: 'Easy', watering: 'Every 7-10 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'echeveria_elegans', scientific: 'Echeveria elegans', commonName: 'Echeveria', family: 'Crassulaceae', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Echeveria_elegans_-_1.png/330px-Echeveria_elegans_-_1.png', careLevel: 'Easy', watering: 'Every 2-3 weeks', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'mentha_spicata', scientific: 'Mentha spicata', commonName: 'Mint', family: 'Lamiaceae', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Minze.jpg/330px-Minze.jpg', careLevel: 'Easy', watering: 'Every 3-5 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'dieffenbachia_seguine', scientific: 'Dieffenbachia seguine', commonName: 'Dumb Cane', family: 'Araceae', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/80/Dieffenbachia_seguine1FKST.jpg', careLevel: 'Medium', watering: 'Every 5-7 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'lavandula_angustifolia', scientific: 'Lavandula angustifolia', commonName: 'Lavender', family: 'Lamiaceae', imageUrl: 'https://bs.plantnet.org/image/o/010ffc8860641c73888c8664743f1527d284f258', careLevel: 'Easy', watering: 'Every 7-10 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'dracaena_fragrans', scientific: 'Dracaena fragrans', commonName: 'Corn Plant', family: 'Asparagaceae', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/db/Dracaena_fragrans_%282%29.jpg', careLevel: 'Easy', watering: 'Every 7-10 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'dypsis_lutescens', scientific: 'Dypsis lutescens', commonName: 'Areca Palm', family: 'Arecaceae', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/22/%E6%95%A3%E5%B0%BE%E8%91%B5Dypsis_lutescens_20210511145013_05.jpg', careLevel: 'Medium', watering: 'Every 7-10 days', indoor: true),
  LibraryPlant(id: 0, plantIdStr: 'cycas_revoluta', scientific: 'Cycas revoluta', commonName: 'Sago Palm', family: 'Cycadaceae', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/3b/Cycas_inflorescence.jpg', careLevel: 'Medium', watering: 'Every 7-10 days', indoor: true),
];
