// Popular plants for Library MVP (hardcoded, replaced by Turso in Stage 5)
// Care data: per-species overrides take priority over preset defaults
import type { PresetCare } from './presets';

export interface PopularPlant {
  id: string;
  scientific: string;
  common_name: string;
  family: string;
  preset: 'Succulents' | 'Standard' | 'Tropical' | 'Herbs';
  plant_type: 'decorative' | 'greens' | 'fruiting';  // determines card type
  image_url: string;          // Wikipedia CC thumbnail
  poisonous_to_pets: boolean;
  poisonous_to_humans: boolean;
  toxicity_note: string;
  category: string;           // for grouping in UI (tropical/succulents/foliage/herbs/flowering/fruiting)
  care?: Partial<PresetCare>; // per-species care overrides (merged with preset defaults)
}

export interface PlantCategory {
  key: string;
  label: string;
  icon: string;               // emoji
  count: number;
}

export const CATEGORIES: PlantCategory[] = [
  { key: 'tropical', label: 'Tropical', icon: '🌴', count: 0 },
  { key: 'succulents', label: 'Succulents', icon: '🌵', count: 0 },
  { key: 'foliage', label: 'Foliage', icon: '🌿', count: 0 },
  { key: 'herbs', label: 'Herbs', icon: '🌱', count: 0 },
  { key: 'flowering', label: 'Flowering', icon: '🌸', count: 0 },
  { key: 'fruiting', label: 'Fruiting', icon: '🍅', count: 0 },
];

// 25 most popular houseplants — sorted alphabetically by scientific name
export const POPULAR_PLANTS: PopularPlant[] = [
  {
    id: 'aloe_vera',
    scientific: 'Aloe vera',
    common_name: 'Aloe Vera',
    family: 'Asphodelaceae',
    preset: 'Succulents',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Aloe_vera_flower_inset.png/330px-Aloe_vera_flower_inset.png',
    poisonous_to_pets: true,
    poisonous_to_humans: false,
    toxicity_note: 'Saponins cause vomiting/diarrhea in pets',
    category: 'succulents',
    care: {
      watering: 'Every 2-3 weeks, soak and dry method',
      watering_winter: 'Once a month or less',
      light: 'Bright direct sun (south window)',
      light_also_ok: 'Bright indirect',
      ppfd_min: 300, ppfd_max: 800, dli_min: 10, dli_max: 25,
      temperature: '13-27\u00B0C (55-80\u00B0F)',
      humidity: 'Low (30-40%)',
      soil: 'Cactus/succulent mix with extra perlite',
      repot: 'Every 2-3 years when rootbound',
      fertilizer: 'Diluted balanced fertilizer once in spring',
      tips: 'Gel inside leaves is medicinal. Let soil dry completely. Needs lots of light to stay compact.',
      common_problems: ['Root rot (overwatering)', 'Soft/mushy leaves (too much water)', 'Brown tips (sunburn or underwatering)'],
      common_pests: ['Mealybugs', 'Scale', 'Aloe mites'],
    },
  },
  {
    id: 'anthurium_andraeanum',
    scientific: 'Anthurium andraeanum',
    common_name: 'Flamingo Flower',
    family: 'Araceae',
    preset: 'Tropical',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/AnthuriumAndraenum.jpg/330px-AnthuriumAndraenum.jpg',
    poisonous_to_pets: true,
    poisonous_to_humans: true,
    toxicity_note: 'Calcium oxalate crystals cause mouth/throat irritation',
    category: 'flowering',
    care: {
      watering: 'Every 5-7 days, keep evenly moist',
      watering_winter: 'Every 7-10 days',
      light: 'Bright indirect light, no direct sun',
      light_also_ok: 'Medium indirect',
      ppfd_min: 150, ppfd_max: 400, dli_min: 6, dli_max: 14,
      temperature: '20-28\u00B0C (68-82\u00B0F)',
      humidity: 'High (60-80%)',
      humidity_action: 'Mist regularly or use a pebble tray. Loves bathroom humidity.',
      soil: 'Well-draining orchid/anthurium mix (bark, perlite, peat)',
      repot: 'Every 2-3 years, likes being slightly rootbound',
      fertilizer: 'High-phosphorus fertilizer monthly in spring/summer',
      tips: 'Blooms last 2-3 months. Wipe leaves to keep them glossy. Remove spent flowers at base.',
      common_problems: ['Green flowers (too much nitrogen)', 'Brown tips (low humidity)', 'Yellow leaves (overwatering)'],
      common_pests: ['Mealybugs', 'Aphids', 'Spider mites'],
    },
  },
  {
    id: 'aspidistra_elatior',
    scientific: 'Aspidistra elatior',
    common_name: 'Cast Iron Plant',
    family: 'Asparagaceae',
    preset: 'Standard',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Aspidistra_elatior1.jpg/330px-Aspidistra_elatior1.jpg',
    poisonous_to_pets: false,
    poisonous_to_humans: false,
    toxicity_note: '',
    category: 'foliage',
    care: {
      watering: 'Every 7-14 days, tolerates drought',
      watering_winter: 'Every 2-3 weeks',
      light: 'Low to medium indirect light',
      light_also_ok: 'Deep shade (very tolerant)',
      ppfd_min: 25, ppfd_max: 150, dli_min: 1, dli_max: 6,
      temperature: '7-29\u00B0C (45-85\u00B0F)',
      humidity: 'Any (very tolerant)',
      humidity_action: 'No special requirements. Handles dry air well.',
      soil: 'Standard potting mix, not fussy',
      repot: 'Every 3-5 years, slow grower',
      fertilizer: 'Light feeding once in spring',
      tips: 'Nearly indestructible. Perfect for dark corners. Tolerates neglect, dust, and temperature extremes.',
      common_problems: ['Brown leaf tips (chlorine in water)', 'Split leaves (mechanical damage)', 'Slow growth (normal)'],
      common_pests: ['Spider mites (rare)', 'Scale (rare)'],
    },
  },
  {
    id: 'calathea_orbifolia',
    scientific: 'Calathea orbifolia',
    common_name: 'Round-leaf Calathea',
    family: 'Marantaceae',
    preset: 'Tropical',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Calathea_orbifolia_2.jpg/330px-Calathea_orbifolia_2.jpg',
    poisonous_to_pets: false,
    poisonous_to_humans: false,
    toxicity_note: '',
    category: 'tropical',
    care: {
      watering: 'Every 5-7 days, keep soil consistently moist',
      watering_winter: 'Every 7-10 days, slightly drier',
      light: 'Medium indirect light, no direct sun',
      light_also_ok: 'Low light (tolerates)',
      ppfd_min: 75, ppfd_max: 200, dli_min: 3, dli_max: 8,
      temperature: '18-24\u00B0C (65-75\u00B0F), sensitive to cold',
      humidity: 'High (60-80%)',
      humidity_action: 'Use humidifier or pebble tray. Mist with distilled water only.',
      soil: 'Well-draining mix with peat, perlite, and orchid bark',
      repot: 'Every 1-2 years in spring',
      fertilizer: 'Monthly with balanced liquid fertilizer in growing season',
      tips: 'Use filtered/distilled water — very sensitive to fluoride. Leaves fold up at night (prayer movement). Rotate weekly for even growth.',
      common_problems: ['Brown edges (hard water or low humidity)', 'Curling leaves (underwatering)', 'Fading patterns (too much sun)'],
      common_pests: ['Spider mites', 'Fungus gnats', 'Mealybugs'],
    },
  },
  {
    id: 'chlorophytum_comosum',
    scientific: 'Chlorophytum comosum',
    common_name: 'Spider Plant',
    family: 'Asparagaceae',
    preset: 'Standard',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Hierbabuena_0611_Revised.jpg/330px-Hierbabuena_0611_Revised.jpg',
    poisonous_to_pets: false,
    poisonous_to_humans: false,
    toxicity_note: '',
    category: 'foliage',
    care: {
      watering: 'Every 7-10 days when top inch is dry',
      watering_winter: 'Every 10-14 days',
      light: 'Bright indirect to medium light',
      light_also_ok: 'Low light (tolerates briefly)',
      ppfd_min: 75, ppfd_max: 250, dli_min: 3, dli_max: 10,
      temperature: '18-27\u00B0C (65-80\u00B0F)',
      humidity: 'Average (40-60%)',
      humidity_action: 'Benefits from occasional misting in dry air.',
      soil: 'Standard potting mix with perlite',
      repot: 'Every 1-2 years in spring, easy to divide',
      fertilizer: 'Monthly with diluted balanced fertilizer spring-fall',
      tips: 'Produces baby "spiderettes" on runners — perfect for propagation. Tolerant and beginner-friendly. NASA air-purifying plant.',
      common_problems: ['Brown tips (fluoride in water)', 'Pale leaves (too much direct sun)', 'No babies (plant too young or too little light)'],
      common_pests: ['Spider mites', 'Whiteflies', 'Mealybugs'],
    },
  },
  {
    id: 'citrus_limon',
    scientific: 'Citrus limon',
    common_name: 'Lemon Tree',
    family: 'Rutaceae',
    preset: 'Standard',
    plant_type: 'fruiting',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/P1030323.JPG/330px-P1030323.JPG',
    poisonous_to_pets: true,
    poisonous_to_humans: false,
    toxicity_note: 'Essential oils and psoralens toxic to cats and dogs',
    category: 'fruiting',
    care: {
      watering: 'Every 5-7 days, keep soil evenly moist',
      watering_winter: 'Every 7-10 days, reduce slightly',
      light: 'Full sun 6-8 hours (south-facing window)',
      light_also_ok: 'Bright indirect (but won\'t fruit well)',
      ppfd_min: 400, ppfd_max: 800, dli_min: 15, dli_max: 30,
      temperature: '13-30\u00B0C (55-86\u00B0F), needs cool nights for fruiting',
      humidity: 'Average (40-60%)',
      humidity_action: 'Mist during flowering to help pollination. Good air circulation.',
      soil: 'Slightly acidic (pH 5.5-6.5), well-draining citrus mix',
      repot: 'Every 2-3 years, one size up only',
      fertilizer: 'Citrus-specific fertilizer every 2 weeks in growing season',
      fertilizer_season: 'Spring through Fall',
      tips: 'Indoor trees need hand-pollination with a brush. Cold period (10-13\u00B0C) in winter triggers blooming. Prune to maintain shape.',
      common_problems: ['Leaf drop (temperature shock or overwatering)', 'No fruit (needs hand-pollination indoors)', 'Yellowing leaves (iron deficiency)'],
      common_pests: ['Scale', 'Spider mites', 'Aphids', 'Leaf miners'],
    },
  },
  {
    id: 'crassula_ovata',
    scientific: 'Crassula ovata',
    common_name: 'Jade Plant',
    family: 'Crassulaceae',
    preset: 'Succulents',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Crassula_ovata_700.jpg/330px-Crassula_ovata_700.jpg',
    poisonous_to_pets: true,
    poisonous_to_humans: false,
    toxicity_note: 'Toxic to cats and dogs if ingested',
    category: 'succulents',
    care: {
      watering: 'Every 2-3 weeks, let dry completely',
      watering_winter: 'Once a month',
      light: 'Bright indirect to direct sun',
      light_also_ok: 'Medium light (grows slower)',
      ppfd_min: 200, ppfd_max: 600, dli_min: 8, dli_max: 20,
      temperature: '15-24\u00B0C (59-75\u00B0F)',
      humidity: 'Low to average (30-50%)',
      soil: 'Well-draining succulent mix with sand',
      repot: 'Every 2-3 years, prefers snug pot',
      fertilizer: 'Diluted balanced fertilizer 2-3 times in growing season',
      tips: 'Can grow into a tree-like form over decades. Stems can be pruned to encourage branching. Symbol of good luck.',
      common_problems: ['Soft/wrinkled leaves (overwatering)', 'Dropping leaves (overwatering or cold)', 'Leggy growth (low light)'],
      common_pests: ['Mealybugs', 'Spider mites', 'Scale'],
    },
  },
  {
    id: 'dracaena_marginata',
    scientific: 'Dracaena marginata',
    common_name: 'Dragon Tree',
    family: 'Asparagaceae',
    preset: 'Standard',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Dracaena_reflexa.JPG/330px-Dracaena_reflexa.JPG',
    poisonous_to_pets: true,
    poisonous_to_humans: false,
    toxicity_note: 'Saponins cause nausea/vomiting in pets',
    category: 'foliage',
    care: {
      watering: 'Every 7-10 days when top half is dry',
      watering_winter: 'Every 2-3 weeks',
      light: 'Bright indirect light, tolerates some direct morning sun',
      light_also_ok: 'Medium to low light',
      ppfd_min: 75, ppfd_max: 300, dli_min: 3, dli_max: 12,
      temperature: '18-27\u00B0C (65-80\u00B0F)',
      humidity: 'Average (40-60%)',
      humidity_action: 'Mist occasionally in dry conditions.',
      soil: 'Well-draining potting mix with perlite',
      repot: 'Every 2 years in spring',
      fertilizer: 'Monthly with balanced liquid fertilizer spring-summer',
      tips: 'Thin trunk with dramatic red-edged leaves. Top-heavy — use a heavier pot. Can reach 2m indoors. Sensitive to fluoride — use filtered water.',
      common_problems: ['Brown tips (fluoride/chlorine in water)', 'Soft trunk (root rot)', 'Dropping lower leaves (normal aging)'],
      common_pests: ['Spider mites', 'Mealybugs', 'Thrips'],
    },
  },
  {
    id: 'dracaena_trifasciata',
    scientific: 'Dracaena trifasciata',
    common_name: 'Snake Plant',
    family: 'Asparagaceae',
    preset: 'Standard',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Snake_Plant_%28Sansevieria_trifasciata_%27Laurentii%27%29.jpg/330px-Snake_Plant_%28Sansevieria_trifasciata_%27Laurentii%27%29.jpg',
    poisonous_to_pets: true,
    poisonous_to_humans: false,
    toxicity_note: 'Saponins cause nausea/vomiting in pets',
    category: 'foliage',
    care: {
      watering: 'Every 10-14 days, let top 2 inches dry',
      watering_winter: 'Every 3-4 weeks',
      light: 'Low to bright indirect light',
      light_also_ok: 'Deep shade (very tolerant)',
      ppfd_min: 25, ppfd_max: 200, dli_min: 1, dli_max: 8,
      temperature: '15-29\u00B0C (59-85\u00B0F)',
      humidity: 'Low to average (30-50%)',
      humidity_action: 'Normal room humidity is fine. Avoid misting.',
      soil: 'Well-draining mix with sand and perlite',
      repot: 'Every 2-3 years, tolerates being rootbound',
      fertilizer: '2-3 times per year with balanced fertilizer',
      tips: 'One of the hardiest houseplants. Converts CO2 to O2 at night (bedroom plant). Propagate easily from leaf cuttings.',
      common_problems: ['Mushy base (root rot from overwatering)', 'Drooping leaves (underwatering)', 'Wrinkled leaves (thirst)'],
      common_pests: ['Mealybugs', 'Fungus gnats', 'Spider mites'],
    },
  },
  {
    id: 'echeveria_elegans',
    scientific: 'Echeveria elegans',
    common_name: 'Mexican Snowball',
    family: 'Crassulaceae',
    preset: 'Succulents',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Echeveria_elegans_-_1.png/330px-Echeveria_elegans_-_1.png',
    poisonous_to_pets: false,
    poisonous_to_humans: false,
    toxicity_note: '',
    category: 'succulents',
    care: {
      watering: 'Every 2-3 weeks, soak and dry completely',
      watering_winter: 'Once a month or less',
      light: 'Bright direct to indirect light',
      light_also_ok: 'Part shade (stretches)',
      ppfd_min: 250, ppfd_max: 700, dli_min: 8, dli_max: 22,
      temperature: '15-27\u00B0C (59-80\u00B0F)',
      humidity: 'Low (30-40%)',
      soil: 'Gritty succulent mix with perlite and coarse sand',
      repot: 'Every 2-3 years in spring',
      fertilizer: 'Once in spring with diluted succulent fertilizer',
      tips: 'Powder on leaves (farina) is protective — don\'t wipe off. Forms beautiful rosettes. Produces offsets easily for propagation.',
      common_problems: ['Etiolation/stretching (not enough light)', 'Mushy center (overwatering)', 'Sunburn (too sudden direct sun)'],
      common_pests: ['Mealybugs', 'Vine weevil', 'Aphids (on flower stalks)'],
    },
  },
  {
    id: 'epipremnum_aureum',
    scientific: 'Epipremnum aureum',
    common_name: 'Pothos',
    family: 'Araceae',
    preset: 'Tropical',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Money_Plant_%28Epipremnum_aureum%29_4.jpg/330px-Money_Plant_%28Epipremnum_aureum%29_4.jpg',
    poisonous_to_pets: true,
    poisonous_to_humans: true,
    toxicity_note: 'Calcium oxalate crystals cause mouth/throat irritation',
    category: 'tropical',
    care: {
      watering: 'Every 7-10 days when top inch is dry',
      watering_winter: 'Every 10-14 days',
      light: 'Low to bright indirect light',
      light_also_ok: 'Very low light (extremely tolerant)',
      ppfd_min: 25, ppfd_max: 200, dli_min: 1, dli_max: 8,
      temperature: '18-29\u00B0C (65-85\u00B0F)',
      humidity: 'Average (40-60%)',
      humidity_action: 'Handles normal room humidity. Benefits from occasional misting.',
      soil: 'Standard potting mix with perlite, well-draining',
      repot: 'Every 1-2 years, prune to control size',
      fertilizer: 'Monthly with balanced liquid fertilizer spring-summer',
      tips: 'Top NASA air-purifying plant. Trails or climbs — versatile for shelves and hanging baskets. Variegated types need more light.',
      common_problems: ['Yellowing leaves (overwatering)', 'Leggy vines (low light)', 'Loss of variegation (not enough light)'],
      common_pests: ['Mealybugs', 'Spider mites', 'Scale'],
    },
  },
  {
    id: 'ficus_elastica',
    scientific: 'Ficus elastica',
    common_name: 'Rubber Plant',
    family: 'Moraceae',
    preset: 'Standard',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Ficus_elastica_leaves_02.JPG/330px-Ficus_elastica_leaves_02.JPG',
    poisonous_to_pets: true,
    poisonous_to_humans: false,
    toxicity_note: 'Sap causes skin irritation in pets',
    category: 'foliage',
    care: {
      watering: 'Every 7-10 days when top 2 inches are dry',
      watering_winter: 'Every 10-14 days',
      light: 'Bright indirect light, tolerates some direct',
      light_also_ok: 'Medium light',
      ppfd_min: 100, ppfd_max: 400, dli_min: 4, dli_max: 14,
      temperature: '16-27\u00B0C (60-80\u00B0F)',
      humidity: 'Average (40-60%)',
      humidity_action: 'Wipe leaves with damp cloth regularly to prevent dust buildup.',
      soil: 'Well-draining standard mix with perlite',
      repot: 'Every 2 years, go one size up',
      fertilizer: 'Monthly with balanced liquid fertilizer spring-fall',
      tips: 'Large, dark, glossy leaves — great statement plant. Avoid moving once positioned. Milky sap can irritate skin.',
      common_problems: ['Dropping leaves (cold draft, overwatering)', 'Brown spots (inconsistent watering)', 'Yellowing (overwatering)'],
      common_pests: ['Mealybugs', 'Scale', 'Spider mites'],
    },
  },
  {
    id: 'ficus_lyrata',
    scientific: 'Ficus lyrata',
    common_name: 'Fiddle Leaf Fig',
    family: 'Moraceae',
    preset: 'Tropical',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Starr_031108-0130_Ficus_lyrata.jpg/330px-Starr_031108-0130_Ficus_lyrata.jpg',
    poisonous_to_pets: true,
    poisonous_to_humans: false,
    toxicity_note: 'Sap causes skin irritation in pets',
    category: 'tropical',
    care: {
      watering: 'Every 7-10 days when top inch is dry',
      watering_winter: 'Every 10-14 days',
      light: 'Bright indirect light, some morning direct',
      light_also_ok: 'Medium indirect',
      ppfd_min: 150, ppfd_max: 400, dli_min: 6, dli_max: 14,
      temperature: '18-27\u00B0C (65-80\u00B0F), sensitive to cold',
      humidity: 'Average to high (50-70%)',
      humidity_action: 'Loves misting. Humidifier nearby helps in winter.',
      soil: 'Well-draining mix with peat, perlite, and bark',
      repot: 'Every 1-2 years when roots emerge from bottom',
      fertilizer: 'Monthly with balanced liquid fertilizer spring-summer',
      tips: 'Dramatic violin-shaped leaves. Don\'t move it once it\'s happy. Sensitive to overwatering — root rot is #1 killer. Wipe leaves monthly.',
      common_problems: ['Brown spots (overwatering)', 'Drooping leaves (underwatering or root rot)', 'No new growth (low light)'],
      common_pests: ['Spider mites', 'Mealybugs', 'Fungus gnats'],
    },
  },
  {
    id: 'haworthia_fasciata',
    scientific: 'Haworthiopsis attenuata',
    common_name: 'Zebra Plant',
    family: 'Asphodelaceae',
    preset: 'Succulents',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Winterbourne_-_Haworthia_attenuata_%286120983526%29.jpg/330px-Winterbourne_-_Haworthia_attenuata_%286120983526%29.jpg',
    poisonous_to_pets: false,
    poisonous_to_humans: false,
    toxicity_note: '',
    category: 'succulents',
    care: {
      watering: 'Every 2-3 weeks, let dry completely',
      watering_winter: 'Once a month',
      light: 'Bright indirect, some direct morning sun',
      light_also_ok: 'Medium indirect',
      ppfd_min: 150, ppfd_max: 500, dli_min: 6, dli_max: 16,
      temperature: '18-27\u00B0C (65-80\u00B0F)',
      humidity: 'Low (30-40%)',
      soil: 'Gritty succulent mix with extra perlite',
      repot: 'Every 2-3 years, small pot preferred',
      fertilizer: 'Once in spring with diluted cactus fertilizer',
      tips: 'White stripes are raised tubercles, not variegation. Compact and perfect for windowsills. Produces offsets for easy propagation.',
      common_problems: ['Brown tips (too much direct sun)', 'Root rot (overwatering)', 'Closing up (not enough light)'],
      common_pests: ['Mealybugs', 'Scale'],
    },
  },
  {
    id: 'mentha_spicata',
    scientific: 'Mentha spicata',
    common_name: 'Spearmint',
    family: 'Lamiaceae',
    preset: 'Herbs',
    plant_type: 'greens',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Minze.jpg/330px-Minze.jpg',
    poisonous_to_pets: false,
    poisonous_to_humans: false,
    toxicity_note: '',
    category: 'herbs',
    care: {
      watering: 'Every 3-5 days, keep soil consistently moist',
      watering_winter: 'Every 5-7 days',
      light: 'Full sun to bright indirect (4-6 hours)',
      light_also_ok: 'Part shade',
      ppfd_min: 200, ppfd_max: 500, dli_min: 8, dli_max: 18,
      temperature: '18-24\u00B0C (65-75\u00B0F)',
      humidity: 'Average (40-60%)',
      humidity_action: 'Good air circulation more important than humidity.',
      soil: 'Light, well-draining potting mix with compost',
      repot: 'Annually or when rootbound',
      fertilizer: 'Every 2 weeks with nitrogen-rich liquid fertilizer',
      fertilizer_season: 'Spring through Fall',
      tips: 'Harvest leaves regularly to promote bushy growth. Pinch off flower buds to keep energy in leaves. Can be invasive — keep contained.',
      common_problems: ['Leggy growth (not enough light)', 'Black spots on leaves (cold damage)', 'Wilting (underwatering)'],
      common_pests: ['Aphids', 'Spider mites', 'Whiteflies'],
    },
  },
  {
    id: 'monstera_deliciosa',
    scientific: 'Monstera deliciosa',
    common_name: 'Swiss Cheese Plant',
    family: 'Araceae',
    preset: 'Tropical',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Monstera_deliciosa2.jpg/330px-Monstera_deliciosa2.jpg',
    poisonous_to_pets: true,
    poisonous_to_humans: true,
    toxicity_note: 'Calcium oxalate crystals cause mouth/throat irritation',
    category: 'tropical',
    care: {
      watering: 'Every 7-10 days when top 2 inches are dry',
      watering_winter: 'Every 10-14 days',
      light: 'Bright indirect light',
      light_also_ok: 'Medium indirect, some direct morning',
      ppfd_min: 100, ppfd_max: 400, dli_min: 4, dli_max: 14,
      temperature: '18-29\u00B0C (65-85\u00B0F)',
      humidity: 'Average to high (50-70%)',
      humidity_action: 'Mist regularly or use pebble tray in dry seasons.',
      soil: 'Chunky mix: bark, perlite, peat (well-aerated)',
      repot: 'Every 1-2 years, provide moss pole for climbing',
      fertilizer: 'Monthly with balanced liquid fertilizer spring-summer',
      tips: 'Iconic split leaves develop with maturity and light. Give a moss pole — aerial roots need to climb. Can grow very large (2m+).',
      common_problems: ['No fenestrations (too young or low light)', 'Yellow leaves (overwatering)', 'Brown edges (low humidity)'],
      common_pests: ['Spider mites', 'Thrips', 'Mealybugs'],
    },
  },
  {
    id: 'ocimum_basilicum',
    scientific: 'Ocimum basilicum',
    common_name: 'Basil',
    family: 'Lamiaceae',
    preset: 'Herbs',
    plant_type: 'greens',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Ocimum_basilicum_8zz.jpg/330px-Ocimum_basilicum_8zz.jpg',
    poisonous_to_pets: false,
    poisonous_to_humans: false,
    toxicity_note: '',
    category: 'herbs',
    care: {
      watering: 'Every 3-5 days, keep soil moist but not soggy',
      watering_winter: 'Every 5-7 days',
      light: 'Full sun 6+ hours (south-facing window)',
      light_also_ok: 'Bright indirect (won\'t be as flavorful)',
      ppfd_min: 300, ppfd_max: 600, dli_min: 12, dli_max: 22,
      temperature: '18-27\u00B0C (65-80\u00B0F), sensitive to cold',
      humidity: 'Average (40-60%)',
      humidity_action: 'Good air circulation matters. Not fussy about humidity.',
      soil: 'Rich, well-draining potting mix with compost',
      repot: 'Every few months or start new from seed (annual)',
      fertilizer: 'Every 2-3 weeks with nitrogen-rich liquid fertilizer',
      fertilizer_season: 'Throughout growing season',
      tips: 'Pinch off flower buds immediately to prevent bolting. Harvest from top, promotes bushy growth. Aromatic essential oils intensify with more sun.',
      common_problems: ['Bolting (too hot or stressed)', 'Yellow/wilting (underwatering)', 'Black spots (fungal from wet leaves)'],
      common_pests: ['Aphids', 'Japanese beetles', 'Slugs'],
    },
  },
  {
    id: 'phalaenopsis_amabilis',
    scientific: 'Phalaenopsis amabilis',
    common_name: 'Moth Orchid',
    family: 'Orchidaceae',
    preset: 'Tropical',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Phalaenopsis_amabilis_Orchi_198.jpg/330px-Phalaenopsis_amabilis_Orchi_198.jpg',
    poisonous_to_pets: false,
    poisonous_to_humans: false,
    toxicity_note: '',
    category: 'flowering',
    care: {
      watering: 'Every 7-10 days, soak bark then let drain',
      watering_winter: 'Every 10-14 days',
      light: 'Bright indirect, no direct sun',
      light_also_ok: 'East-facing window',
      ppfd_min: 100, ppfd_max: 300, dli_min: 4, dli_max: 12,
      temperature: '18-27\u00B0C (65-80\u00B0F), night drop 5\u00B0C helps',
      humidity: 'Average to high (50-70%)',
      humidity_action: 'Light misting helps, but don\'t let water sit in crown.',
      soil: 'Orchid bark mix (bark, sphagnum, perlite). No regular soil!',
      repot: 'Every 2-3 years after flowering, when bark decomposes',
      fertilizer: 'Orchid-specific fertilizer every 2 weeks in growing season',
      fertilizer_season: 'Spring-Fall',
      tips: 'Blooms last 2-3 months. After flowers drop, cut spike above a node for reblooming. Roots need air — clear pots work best.',
      common_problems: ['Bud blast (temperature change)', 'Wrinkled leaves (dehydrated roots)', 'Yellowing leaves (overwatering)'],
      common_pests: ['Mealybugs', 'Scale', 'Thrips'],
    },
  },
  {
    id: 'philodendron_hederaceum',
    scientific: 'Philodendron hederaceum',
    common_name: 'Heartleaf Philodendron',
    family: 'Araceae',
    preset: 'Tropical',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Philodendron_scandens_subsp_oxycardium2.jpg/330px-Philodendron_scandens_subsp_oxycardium2.jpg',
    poisonous_to_pets: true,
    poisonous_to_humans: true,
    toxicity_note: 'Calcium oxalate crystals cause mouth/throat irritation',
    category: 'tropical',
    care: {
      watering: 'Every 7-10 days when top inch is dry',
      watering_winter: 'Every 10-14 days',
      light: 'Low to bright indirect light',
      light_also_ok: 'Very low light (extremely tolerant)',
      ppfd_min: 25, ppfd_max: 200, dli_min: 1, dli_max: 8,
      temperature: '18-27\u00B0C (65-80\u00B0F)',
      humidity: 'Average (40-60%)',
      humidity_action: 'Tolerant. Benefits from misting in dry conditions.',
      soil: 'Well-draining aroid mix (peat, perlite, bark)',
      repot: 'Every 1-2 years in spring',
      fertilizer: 'Monthly with balanced liquid fertilizer spring-summer',
      tips: 'Heart-shaped leaves, trailing habit. Perfect for hanging baskets or shelves. Very forgiving for beginners. Fast grower.',
      common_problems: ['Yellowing leaves (overwatering)', 'Small leaves (not enough light)', 'Leggy growth (too little light)'],
      common_pests: ['Mealybugs', 'Spider mites', 'Fungus gnats'],
    },
  },
  {
    id: 'saintpaulia_ionantha',
    scientific: 'Streptocarpus sect. Saintpaulia',
    common_name: 'African Violet',
    family: 'Gesneriaceae',
    preset: 'Standard',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Saintpaulia_ionantha.jpg/330px-Saintpaulia_ionantha.jpg',
    poisonous_to_pets: false,
    poisonous_to_humans: false,
    toxicity_note: '',
    category: 'flowering',
    care: {
      watering: 'Water from bottom when top is dry, every 5-7 days',
      watering_winter: 'Every 7-10 days',
      light: 'Bright indirect light, no direct sun',
      light_also_ok: 'Fluorescent/grow lights work great',
      ppfd_min: 100, ppfd_max: 300, dli_min: 4, dli_max: 12,
      temperature: '18-24\u00B0C (65-75\u00B0F), consistent preferred',
      humidity: 'Average to high (50-60%)',
      humidity_action: 'Place on pebble tray. Never mist leaves directly (causes spots).',
      soil: 'Light African violet mix (peat-based, well-draining)',
      repot: 'Annually in spring, shallow pot (1/3 of plant diameter)',
      fertilizer: 'Every 2 weeks with African violet fertilizer in growing season',
      fertilizer_season: 'Year-round under grow lights, or spring-fall',
      tips: 'Flowers almost year-round with enough light. Water from bottom to avoid leaf spots. Remove dead flowers to encourage new blooms.',
      common_problems: ['Crown rot (water on leaves/crown)', 'No flowers (not enough light)', 'Powdery mildew (poor air circulation)'],
      common_pests: ['Mealybugs', 'Cyclamen mites', 'Thrips'],
    },
  },
  {
    id: 'rosmarinus_officinalis',
    scientific: 'Salvia rosmarinus',
    common_name: 'Rosemary',
    family: 'Lamiaceae',
    preset: 'Herbs',
    plant_type: 'greens',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Rosemary_in_bloom.JPG/330px-Rosemary_in_bloom.JPG',
    poisonous_to_pets: false,
    poisonous_to_humans: false,
    toxicity_note: '',
    category: 'herbs',
    care: {
      watering: 'Every 7-10 days when top inch is dry',
      watering_winter: 'Every 10-14 days, keep slightly drier',
      light: 'Full sun 6+ hours (south-facing window)',
      light_also_ok: 'Bright indirect (survives but less flavorful)',
      ppfd_min: 300, ppfd_max: 600, dli_min: 12, dli_max: 22,
      temperature: '10-24\u00B0C (50-75\u00B0F), tolerates light frost',
      humidity: 'Low to average (30-50%)',
      humidity_action: 'Prefers drier conditions. Good air circulation essential.',
      soil: 'Well-draining, sandy, slightly alkaline soil',
      repot: 'Every 1-2 years, terracotta pot preferred',
      fertilizer: 'Light feeding once in spring',
      fertilizer_season: 'Spring only',
      tips: 'Woody Mediterranean herb. Thrives in poor soil. Prune after flowering to stay bushy. Excellent for cooking and aromatherapy.',
      common_problems: ['Crispy leaves (underwatering or too dry air indoors)', 'Leggy growth (not enough light)', 'Root rot (wet soil)'],
      common_pests: ['Spider mites', 'Whiteflies', 'Powdery mildew (not a pest but common issue)'],
    },
  },
  {
    id: 'sedum_morganianum',
    scientific: 'Sedum morganianum',
    common_name: "Burro's Tail",
    family: 'Crassulaceae',
    preset: 'Succulents',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Donkey%27s_tail_in_bloom_March_06.jpg/330px-Donkey%27s_tail_in_bloom_March_06.jpg',
    poisonous_to_pets: false,
    poisonous_to_humans: false,
    toxicity_note: '',
    category: 'succulents',
    care: {
      watering: 'Every 2-3 weeks, let dry between waterings',
      watering_winter: 'Once a month',
      light: 'Bright indirect light, some morning direct',
      light_also_ok: 'Part shade (grows slower)',
      ppfd_min: 150, ppfd_max: 500, dli_min: 6, dli_max: 16,
      temperature: '18-27\u00B0C (65-80\u00B0F)',
      humidity: 'Low (30-40%)',
      soil: 'Well-draining succulent/cactus mix',
      repot: 'Every 2-3 years, very carefully (leaves detach easily)',
      fertilizer: 'Once in spring with diluted succulent fertilizer',
      tips: 'Trailing succulent — perfect for hanging baskets. Leaves fall off easily but each one can propagate. Handle gently! Stunning cascading effect.',
      common_problems: ['Shriveled leaves (underwatering)', 'Leaf drop (overwatering or handling)', 'Soft/translucent leaves (root rot)'],
      common_pests: ['Mealybugs', 'Aphids'],
    },
  },
  {
    id: 'spathiphyllum_wallisii',
    scientific: 'Spathiphyllum wallisii',
    common_name: 'Peace Lily',
    family: 'Araceae',
    preset: 'Tropical',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Spathiphyllum_cochlearispathum_RTBG.jpg/330px-Spathiphyllum_cochlearispathum_RTBG.jpg',
    poisonous_to_pets: true,
    poisonous_to_humans: true,
    toxicity_note: 'Calcium oxalate crystals cause mouth/throat irritation',
    category: 'tropical',
    care: {
      watering: 'Every 5-7 days, keep evenly moist',
      watering_winter: 'Every 7-10 days',
      light: 'Low to bright indirect light',
      light_also_ok: 'Very low light (tolerant)',
      ppfd_min: 25, ppfd_max: 200, dli_min: 1, dli_max: 8,
      temperature: '18-27\u00B0C (65-80\u00B0F)',
      humidity: 'Average to high (50-70%)',
      humidity_action: 'Mist regularly or use a pebble tray. Loves humidity.',
      soil: 'Standard potting mix with perlite, well-draining',
      repot: 'Every 1-2 years in spring',
      fertilizer: 'Monthly with balanced liquid fertilizer spring-summer',
      tips: 'Elegantly droops when thirsty — easy watering indicator! White sail-like flowers appear with adequate light. NASA air-purifying plant.',
      common_problems: ['Brown tips (hard water, low humidity)', 'Yellow leaves (overwatering)', 'No flowers (needs brighter light)'],
      common_pests: ['Mealybugs', 'Spider mites', 'Fungus gnats'],
    },
  },
  {
    id: 'strelitzia_reginae',
    scientific: 'Strelitzia reginae',
    common_name: 'Bird of Paradise',
    family: 'Strelitziaceae',
    preset: 'Tropical',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Bird_of_Paradise_flower.JPG/330px-Bird_of_Paradise_flower.JPG',
    poisonous_to_pets: true,
    poisonous_to_humans: false,
    toxicity_note: 'Mildly toxic if ingested by pets',
    category: 'tropical',
    care: {
      watering: 'Every 7-10 days when top 2 inches are dry',
      watering_winter: 'Every 10-14 days',
      light: 'Bright direct to indirect light (6+ hours)',
      light_also_ok: 'Bright indirect',
      ppfd_min: 200, ppfd_max: 600, dli_min: 8, dli_max: 20,
      temperature: '18-30\u00B0C (65-86\u00B0F)',
      humidity: 'Average (40-60%)',
      humidity_action: 'Normal room humidity. Mist occasionally.',
      soil: 'Well-draining potting mix with perlite and sand',
      repot: 'Every 2-3 years, large pot needed (grows big)',
      fertilizer: 'Monthly with balanced fertilizer spring-summer',
      tips: 'Dramatic bird-like flowers require maturity (5+ years) and bright light. Grows large (1.5m+). Fan-shaped leaf arrangement. Slow grower.',
      common_problems: ['No flowers (too young, not enough light)', 'Brown leaves (too much direct sun)', 'Curling leaves (underwatering)'],
      common_pests: ['Spider mites', 'Mealybugs', 'Scale'],
    },
  },
  {
    id: 'zamioculcas_zamiifolia',
    scientific: 'Zamioculcas zamiifolia',
    common_name: 'ZZ Plant',
    family: 'Araceae',
    preset: 'Standard',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Zamioculcas_zamiifolia_1.jpg/330px-Zamioculcas_zamiifolia_1.jpg',
    poisonous_to_pets: true,
    poisonous_to_humans: true,
    toxicity_note: 'Calcium oxalate crystals cause mouth/throat irritation',
    category: 'foliage',
    care: {
      watering: 'Every 2-3 weeks, let dry completely',
      watering_winter: 'Every 3-4 weeks, very drought tolerant',
      light: 'Low to bright indirect light',
      light_also_ok: 'Very low light (extremely tolerant)',
      ppfd_min: 25, ppfd_max: 200, dli_min: 1, dli_max: 8,
      temperature: '18-27\u00B0C (65-80\u00B0F)',
      humidity: 'Low to average (30-50%)',
      humidity_action: 'No special requirements. Very tolerant.',
      soil: 'Well-draining standard mix with perlite and sand',
      repot: 'Every 2-3 years, tolerates being rootbound',
      fertilizer: '2-3 times per year with balanced fertilizer',
      tips: 'Bulbous rhizomes store water — extremely drought tolerant. Nearly impossible to kill. Glossy, architectural leaves. Slow grower.',
      common_problems: ['Yellowing leaves (overwatering — most common issue)', 'Soft stems (root rot)', 'Brown spots (too much direct sun)'],
      common_pests: ['Mealybugs', 'Scale', 'Aphids (rare)'],
    },
  },
];

// Compute category counts
CATEGORIES.forEach((cat) => {
  cat.count = POPULAR_PLANTS.filter((p) => p.category === cat.key).length;
});
