// Popular plants for Library MVP (hardcoded, replaced by Turso in Stage 5)
// Care data matches backend PRESET_DETAILS + FAMILY_PRESETS + TOXIC_FAMILIES

export interface PopularPlant {
  id: string;
  scientific: string;
  common_name: string;
  family: string;
  preset: 'Succulents' | 'Standard' | 'Tropical' | 'Herbs';
  plant_type: 'decorative' | 'greens' | 'fruiting';  // determines card type
  image_url: string;          // Wikipedia CC thumbnail
  poisonous_to_pets: boolean;
  poisonous_to_humans: boolean;
  toxicity_note: string;
  category: string;           // for grouping in UI (tropical/succulents/foliage/herbs/flowering/fruiting)
}

export interface PlantCategory {
  key: string;
  label: string;
  icon: string;               // emoji
  count: number;
}

export const CATEGORIES: PlantCategory[] = [
  { key: 'tropical', label: 'Tropical', icon: '🌴', count: 0 },
  { key: 'succulents', label: 'Succulents', icon: '🌵', count: 0 },
  { key: 'foliage', label: 'Foliage', icon: '🌿', count: 0 },
  { key: 'herbs', label: 'Herbs', icon: '🌱', count: 0 },
  { key: 'flowering', label: 'Flowering', icon: '🌸', count: 0 },
  { key: 'fruiting', label: 'Fruiting', icon: '🍅', count: 0 },
];

// 25 most popular houseplants — sorted alphabetically by scientific name
export const POPULAR_PLANTS: PopularPlant[] = [
  {
    id: 'aloe_vera',
    scientific: 'Aloe vera',
    common_name: 'Aloe Vera',
    family: 'Asphodelaceae',
    preset: 'Succulents',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Aloe_vera_flower_inridge.jpg/120px-Aloe_vera_flower_inridge.jpg',
    poisonous_to_pets: true,
    poisonous_to_humans: false,
    toxicity_note: 'Saponins cause vomiting/diarrhea in pets',
    category: 'succulents',
  },
  {
    id: 'anthurium_andraeanum',
    scientific: 'Anthurium andraeanum',
    common_name: 'Flamingo Flower',
    family: 'Araceae',
    preset: 'Tropical',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Anthurium_andraeanum_1.jpg/120px-Anthurium_andraeanum_1.jpg',
    poisonous_to_pets: true,
    poisonous_to_humans: true,
    toxicity_note: 'Calcium oxalate crystals cause mouth/throat irritation',
    category: 'flowering',
  },
  {
    id: 'aspidistra_elatior',
    scientific: 'Aspidistra elatior',
    common_name: 'Cast Iron Plant',
    family: 'Asparagaceae',
    preset: 'Standard',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Aspidistra_elatior1.jpg/120px-Aspidistra_elatior1.jpg',
    poisonous_to_pets: false,
    poisonous_to_humans: false,
    toxicity_note: '',
    category: 'foliage',
  },
  {
    id: 'calathea_orbifolia',
    scientific: 'Calathea orbifolia',
    common_name: 'Round-leaf Calathea',
    family: 'Marantaceae',
    preset: 'Tropical',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Calathea_Orbifolia.jpg/120px-Calathea_Orbifolia.jpg',
    poisonous_to_pets: false,
    poisonous_to_humans: false,
    toxicity_note: '',
    category: 'tropical',
  },
  {
    id: 'chlorophytum_comosum',
    scientific: 'Chlorophytum comosum',
    common_name: 'Spider Plant',
    family: 'Asparagaceae',
    preset: 'Standard',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Chlorophytum_comosum_%27Vittatum%27_1.jpg/120px-Chlorophytum_comosum_%27Vittatum%27_1.jpg',
    poisonous_to_pets: false,
    poisonous_to_humans: false,
    toxicity_note: '',
    category: 'foliage',
  },
  {
    id: 'citrus_limon',
    scientific: 'Citrus limon',
    common_name: 'Lemon Tree',
    family: 'Rutaceae',
    preset: 'Standard',
    plant_type: 'fruiting',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Lemon_-_whole_and_split.jpg/120px-Lemon_-_whole_and_split.jpg',
    poisonous_to_pets: true,
    poisonous_to_humans: false,
    toxicity_note: 'Essential oils and psoralens toxic to cats and dogs',
    category: 'fruiting',
  },
  {
    id: 'crassula_ovata',
    scientific: 'Crassula ovata',
    common_name: 'Jade Plant',
    family: 'Crassulaceae',
    preset: 'Succulents',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Crassula_ovata_-_2.jpg/120px-Crassula_ovata_-_2.jpg',
    poisonous_to_pets: true,
    poisonous_to_humans: false,
    toxicity_note: 'Toxic to cats and dogs if ingested',
    category: 'succulents',
  },
  {
    id: 'dracaena_marginata',
    scientific: 'Dracaena marginata',
    common_name: 'Dragon Tree',
    family: 'Asparagaceae',
    preset: 'Standard',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Dracaena_marginata.jpg/120px-Dracaena_marginata.jpg',
    poisonous_to_pets: true,
    poisonous_to_humans: false,
    toxicity_note: 'Saponins cause nausea/vomiting in pets',
    category: 'foliage',
  },
  {
    id: 'dracaena_trifasciata',
    scientific: 'Dracaena trifasciata',
    common_name: 'Snake Plant',
    family: 'Asparagaceae',
    preset: 'Standard',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Snake_Plant_%28Sansevieria_trifasciata_%27Laurentii%27%29.jpg/120px-Snake_Plant_%28Sansevieria_trifasciata_%27Laurentii%27%29.jpg',
    poisonous_to_pets: true,
    poisonous_to_humans: false,
    toxicity_note: 'Saponins cause nausea/vomiting in pets',
    category: 'foliage',
  },
  {
    id: 'echeveria_elegans',
    scientific: 'Echeveria elegans',
    common_name: 'Mexican Snowball',
    family: 'Crassulaceae',
    preset: 'Succulents',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Echeveria_elegans_1.jpg/120px-Echeveria_elegans_1.jpg',
    poisonous_to_pets: false,
    poisonous_to_humans: false,
    toxicity_note: '',
    category: 'succulents',
  },
  {
    id: 'epipremnum_aureum',
    scientific: 'Epipremnum aureum',
    common_name: 'Pothos',
    family: 'Araceae',
    preset: 'Tropical',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Epipremnum_aureum_31082012.jpg/120px-Epipremnum_aureum_31082012.jpg',
    poisonous_to_pets: true,
    poisonous_to_humans: true,
    toxicity_note: 'Calcium oxalate crystals cause mouth/throat irritation',
    category: 'tropical',
  },
  {
    id: 'ficus_elastica',
    scientific: 'Ficus elastica',
    common_name: 'Rubber Plant',
    family: 'Moraceae',
    preset: 'Standard',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Starr_080117-1761_Ficus_elastica.jpg/120px-Starr_080117-1761_Ficus_elastica.jpg',
    poisonous_to_pets: true,
    poisonous_to_humans: false,
    toxicity_note: 'Sap causes skin irritation in pets',
    category: 'foliage',
  },
  {
    id: 'ficus_lyrata',
    scientific: 'Ficus lyrata',
    common_name: 'Fiddle Leaf Fig',
    family: 'Moraceae',
    preset: 'Tropical',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Ficus_lyrata_01_by_Line1.jpg/120px-Ficus_lyrata_01_by_Line1.jpg',
    poisonous_to_pets: true,
    poisonous_to_humans: false,
    toxicity_note: 'Sap causes skin irritation in pets',
    category: 'tropical',
  },
  {
    id: 'haworthia_fasciata',
    scientific: 'Haworthiopsis attenuata',
    common_name: 'Zebra Plant',
    family: 'Asphodelaceae',
    preset: 'Succulents',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Haworthia_fasciata.jpg/120px-Haworthia_fasciata.jpg',
    poisonous_to_pets: false,
    poisonous_to_humans: false,
    toxicity_note: '',
    category: 'succulents',
  },
  {
    id: 'mentha_spicata',
    scientific: 'Mentha spicata',
    common_name: 'Spearmint',
    family: 'Lamiaceae',
    preset: 'Herbs',
    plant_type: 'greens',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Mentha_spicata_-_Spearmint.jpg/120px-Mentha_spicata_-_Spearmint.jpg',
    poisonous_to_pets: false,
    poisonous_to_humans: false,
    toxicity_note: '',
    category: 'herbs',
  },
  {
    id: 'monstera_deliciosa',
    scientific: 'Monstera deliciosa',
    common_name: 'Swiss Cheese Plant',
    family: 'Araceae',
    preset: 'Tropical',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Monstera_deliciosa2.jpg/120px-Monstera_deliciosa2.jpg',
    poisonous_to_pets: true,
    poisonous_to_humans: true,
    toxicity_note: 'Calcium oxalate crystals cause mouth/throat irritation',
    category: 'tropical',
  },
  {
    id: 'ocimum_basilicum',
    scientific: 'Ocimum basilicum',
    common_name: 'Basil',
    family: 'Lamiaceae',
    preset: 'Herbs',
    plant_type: 'greens',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Basil-Basilico-Ocimum_basilicum-albahaca.jpg/120px-Basil-Basilico-Ocimum_basilicum-albahaca.jpg',
    poisonous_to_pets: false,
    poisonous_to_humans: false,
    toxicity_note: '',
    category: 'herbs',
  },
  {
    id: 'phalaenopsis_amabilis',
    scientific: 'Phalaenopsis amabilis',
    common_name: 'Moth Orchid',
    family: 'Orchidaceae',
    preset: 'Tropical',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Phalaenopsis_amabilis_Orchi_137.jpg/120px-Phalaenopsis_amabilis_Orchi_137.jpg',
    poisonous_to_pets: false,
    poisonous_to_humans: false,
    toxicity_note: '',
    category: 'flowering',
  },
  {
    id: 'philodendron_hederaceum',
    scientific: 'Philodendron hederaceum',
    common_name: 'Heartleaf Philodendron',
    family: 'Araceae',
    preset: 'Tropical',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Philodendron_hederaceum_var._oxycardium_%28Schott%29_Bunting.jpg/120px-Philodendron_hederaceum_var._oxycardium_%28Schott%29_Bunting.jpg',
    poisonous_to_pets: true,
    poisonous_to_humans: true,
    toxicity_note: 'Calcium oxalate crystals cause mouth/throat irritation',
    category: 'tropical',
  },
  {
    id: 'saintpaulia_ionantha',
    scientific: 'Streptocarpus sect. Saintpaulia',
    common_name: 'African Violet',
    family: 'Gesneriaceae',
    preset: 'Standard',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Saintpaulia_ionantha.jpg/120px-Saintpaulia_ionantha.jpg',
    poisonous_to_pets: false,
    poisonous_to_humans: false,
    toxicity_note: '',
    category: 'flowering',
  },
  {
    id: 'rosmarinus_officinalis',
    scientific: 'Salvia rosmarinus',
    common_name: 'Rosemary',
    family: 'Lamiaceae',
    preset: 'Herbs',
    plant_type: 'greens',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Rosemary_bush.jpg/120px-Rosemary_bush.jpg',
    poisonous_to_pets: false,
    poisonous_to_humans: false,
    toxicity_note: '',
    category: 'herbs',
  },
  {
    id: 'sedum_morganianum',
    scientific: 'Sedum morganianum',
    common_name: "Burro's Tail",
    family: 'Crassulaceae',
    preset: 'Succulents',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Sedum_morganianum_%281%29.jpg/120px-Sedum_morganianum_%281%29.jpg',
    poisonous_to_pets: false,
    poisonous_to_humans: false,
    toxicity_note: '',
    category: 'succulents',
  },
  {
    id: 'spathiphyllum_wallisii',
    scientific: 'Spathiphyllum wallisii',
    common_name: 'Peace Lily',
    family: 'Araceae',
    preset: 'Tropical',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Spathiphyllum_cochlearispathum_RTBG.jpg/120px-Spathiphyllum_cochlearispathum_RTBG.jpg',
    poisonous_to_pets: true,
    poisonous_to_humans: true,
    toxicity_note: 'Calcium oxalate crystals cause mouth/throat irritation',
    category: 'tropical',
  },
  {
    id: 'strelitzia_reginae',
    scientific: 'Strelitzia reginae',
    common_name: 'Bird of Paradise',
    family: 'Strelitziaceae',
    preset: 'Tropical',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Strelitzia_reginae_%28Bird_of_Paradise%29.jpg/120px-Strelitzia_reginae_%28Bird_of_Paradise%29.jpg',
    poisonous_to_pets: true,
    poisonous_to_humans: false,
    toxicity_note: 'Mildly toxic if ingested by pets',
    category: 'tropical',
  },
  {
    id: 'zamioculcas_zamiifolia',
    scientific: 'Zamioculcas zamiifolia',
    common_name: 'ZZ Plant',
    family: 'Araceae',
    preset: 'Standard',
    plant_type: 'decorative',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Zamioculcas_zamiifolia_1.jpg/120px-Zamioculcas_zamiifolia_1.jpg',
    poisonous_to_pets: true,
    poisonous_to_humans: true,
    toxicity_note: 'Calcium oxalate crystals cause mouth/throat irritation',
    category: 'foliage',
  },
];

// Compute category counts
CATEGORIES.forEach((cat) => {
  cat.count = POPULAR_PLANTS.filter((p) => p.category === cat.key).length;
});
